/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Palabras;
import javax.swing.ImageIcon;

/**
 *
 * @author Edison
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    Palabras[] p;
    Palabras palabra1, palabra2, palabra3, palabra4, palabra5, palabra6, palabra7, palabra8, palabra9, palabra10;
    Palabras pr;
    char[] letra;
    int c, cn, cl;
    ImageIcon i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11;

    public VentanaPrincipal() {
        initComponents();
        cn = 0;
        i1 = new ImageIcon("1.png");
        i2 = new ImageIcon("2.png");
        i3 = new ImageIcon("3.png");
        i4 = new ImageIcon("4.png");
        i5 = new ImageIcon("5.png");
        i6 = new ImageIcon("6.png");
        i7 = new ImageIcon("7.png");
        i8 = new ImageIcon("8.png");
        i9 = new ImageIcon("9.png");
        i10 = new ImageIcon("10.png");
        i11 = new ImageIcon("11.png");;
        c = 0;
        p = new Palabras[10];
        palabra1 = new Palabras();
        palabra2 = new Palabras();
        palabra3 = new Palabras();
        palabra4 = new Palabras();
        palabra5 = new Palabras();
        palabra6 = new Palabras();
        palabra7 = new Palabras();
        palabra8 = new Palabras();
        palabra9 = new Palabras();
        palabra10 = new Palabras();
        pr = new Palabras();
        palabra1.setNombre("samsung");
        palabra1.setPista("Marca De Celular");
        p[0] = palabra1;
        palabra2.setNombre("gato");
        palabra2.setPista("Animal Domestico");
        p[1] = palabra2;
        palabra3.setNombre("tenis");
        palabra3.setPista("Deporte");
        p[2] = palabra3;
        palabra4.setNombre("guitarra");
        palabra4.setPista("Instrumento Musical");
        p[3] = palabra4;
        palabra5.setNombre("violeta");
        palabra5.setPista("Color");
        p[4] = palabra5;
        palabra6.setNombre("toyota");
        palabra6.setPista("Marca de carro");
        p[5] = palabra6;
        palabra7.setNombre("rock");
        palabra7.setPista("Genero Musical");
        p[6] = palabra7;
        palabra8.setNombre("azuay");
        palabra8.setPista("Provincia del Ecuador");
        p[7] = palabra8;
        palabra9.setNombre("colombia");
        palabra9.setPista("País Latinoamericano");
        p[8] = palabra9;
        palabra10.setNombre("europa");
        palabra10.setPista("Continente");
        p[9] = palabra10;
        generarPalabra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ima = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        p1 = new javax.swing.JTextField();
        p2 = new javax.swing.JTextField();
        p3 = new javax.swing.JTextField();
        p4 = new javax.swing.JTextField();
        p5 = new javax.swing.JTextField();
        p6 = new javax.swing.JTextField();
        p7 = new javax.swing.JTextField();
        p8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlPista = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/1.png"))); // NOI18N

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });

        p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2ActionPerformed(evt);
            }
        });

        p3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p3ActionPerformed(evt);
            }
        });

        p4.setToolTipText("");
        p4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p4ActionPerformed(evt);
            }
        });

        p5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p5ActionPerformed(evt);
            }
        });

        p6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p6ActionPerformed(evt);
            }
        });

        p7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p7ActionPerformed(evt);
            }
        });

        p8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pista:");

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ima, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPista, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ima, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlPista, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jlResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        if (p1.getText().equals(String.valueOf(letra[0]))) {
            p1.setEditable(false);
            cn++;
            comprovarVictoria();
        } else {
            error();
        }
    }//GEN-LAST:event_p1ActionPerformed

    private void p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2ActionPerformed
        if (p2.getText().equals(String.valueOf(letra[1]))) {
            p2.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p2ActionPerformed

    private void p3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p3ActionPerformed
        if (p3.getText().equals(String.valueOf(letra[2]))) {
            p3.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p3ActionPerformed

    private void p4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p4ActionPerformed
        if (p4.getText().equals(String.valueOf(letra[3]))) {
            p4.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p4ActionPerformed

    private void p5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p5ActionPerformed
        if (p5.getText().equals(String.valueOf(letra[4]))) {
            p5.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p5ActionPerformed

    private void p6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p6ActionPerformed
        if (p6.getText().equals(String.valueOf(letra[5]))) {
            p6.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p6ActionPerformed

    private void p7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p7ActionPerformed
        if (p7.getText().equals(String.valueOf(letra[6]))) {
            p7.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p7ActionPerformed

    private void p8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p8ActionPerformed
        if (p8.getText().equals(String.valueOf(letra[7]))) {
            p8.setEditable(false);
            cn++;
            comprovarVictoria();
        }else {
            error();
        }
    }//GEN-LAST:event_p8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        VentanaPrincipal.main (null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ima;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlPista;
    private javax.swing.JLabel jlResultado;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField p2;
    private javax.swing.JTextField p3;
    private javax.swing.JTextField p4;
    private javax.swing.JTextField p5;
    private javax.swing.JTextField p6;
    private javax.swing.JTextField p7;
    private javax.swing.JTextField p8;
    // End of variables declaration//GEN-END:variables

    private void generarPalabra() {
        int n = (int) (Math.random() * 10);
        pr = p[n];
        jlPista.setText(pr.getPista());
        if (pr.getNombre().length() == 4) {
            p8.setVisible(false);
            p7.setVisible(false);
            p6.setVisible(false);
            p5.setVisible(false);
        } else if (pr.getNombre().length() == 5) {
            p8.setVisible(false);
            p7.setVisible(false);
            p6.setVisible(false);
        } else if (pr.getNombre().length() == 6) {
            p8.setVisible(false);
            p7.setVisible(false);
        } else if (pr.getNombre().length() == 7) {
            p8.setVisible(false);
        }
        n = (int) (Math.random() * pr.getNombre().length());
        letra = pr.getNombre().toCharArray();
        char l = letra[n];
        if (l == letra[0]) {
            p1.setText(String.valueOf(l));
            p1.setEditable(false);
            cn++;
        }
        if (l == letra[1]) {
            p2.setText(String.valueOf(l));
            p2.setEditable(false);
            cn++;
        }
        if (l == letra[2]) {
            p3.setText(String.valueOf(l));
            p3.setEditable(false);
            cn++;
        }
        if (l == letra[3]) {
            p4.setText(String.valueOf(l));
            p4.setEditable(false);
            cn++;
        }
        if (letra.length > 4) {
            if (l == letra[4]) {
                p5.setText(String.valueOf(l));
                p5.setEditable(false);
                cn++;
            }
            if (letra.length > 5) {
                if (l == letra[5]) {
                    p6.setText(String.valueOf(l));
                    p6.setEditable(false);
                    cn++;
                }
                if (letra.length > 6) {
                    if (l == letra[6]) {
                        p7.setText(String.valueOf(l));
                        p7.setEditable(false);
                        cn++;
                    }
                    if (letra.length > 7) {
                        if (l == letra[7]) {
                            p8.setText(String.valueOf(l));
                            p8.setEditable(false);
                            cn++;
                        }
                    }
                }

            }

        }

    }

    private void error() {
        c++;
        if (c == 1) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/2.png")));
        } else if (c == 2) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/3.png")));
        } else if (c == 3) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/4.png")));
        } else if (c == 4) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/5.png")));
        } else if (c == 5) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/6.png")));
        } else if (c == 6) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/7.png")));
        } else if (c == 7) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/8.png")));
        } else if (c == 8) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/9.png")));
        } else if (c == 9) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/10.png")));
        } else if (c == 10) {
            ima.setIcon(new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/11.png")));
            p1.setEditable(false);
            p2.setEditable(false);
            p3.setEditable(false);
            p4.setEditable(false);
            p5.setEditable(false);
            p6.setEditable(false);
            p7.setEditable(false);
            p8.setEditable(false);
            jlResultado.setText("Perdiste");
        }

    }

    private void comprovarVictoria() {
        if(cn == pr.getNombre().length()){
            jlResultado.setText("Ganaste");
        }
    }
}
